function par_print(subpar)
% function par_print(subpar)
% Wrapper function for spm_print to capture what's in the graphics window
% and dump it to the par.logdir directory
%
% subpar refers to either the subject number (in string notation) or
% the par struct generated by par = par_params(subject)
% 
% jbh 7/24/08

% ---load par params if need be---
if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end


origdir = pwd;

if ~exist(par.logdir, 'dir'); mkdir(par.logdir); end

cd(par.logdir);
spm_print;
cd(origdir)

