function par_coregwrapper(subpar)
% function par_coregwrapper(subpar)
% coregisters inplane anat to mean func, and hires to inplane
%
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end



% coreg func to inplane
fprintf('---Coreg inplane for %s---\n',par.substr);

%refimg = par.cor_meanfunc;
%sourceimg = par.inplaneimg;

sourceimg = [par.cor_meanfunc(1:88) 'run01.nii'];
refimg = par.inplaneimg;

par_coreg(refimg, sourceimg);
par_print(par); %print out ps

fprintf('---Coreg inplane COMPLETED for %s---\n',par.substr);



cd(origdir);