function par_makespec(subpar)
% function par_makespec(subpar)
% makes spec mask
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% 
% jbh 7/23/08

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end

% make specmask...
fprintf('---Specmask for %s---\n',par.substr);

graywrimg = par.graywrimg;
grwrflags = par.specwrflags;
[grpth,grnm] = fileparts(graywrimg);
grmatname        = fullfile(grpth,[grnm '_sn.mat']);

grsegs = par.grsegs;
maskimg = par.maskimg;
wmaskimg = par.wmaskimg;
swmaskimg = par.swmaskimg;
tswmaskimg = par.tswmaskimg;
twmaskimg = par.twmaskimg;
addsegs = par.addsegs;
maskthresh = par.maskthresh;
% add segmented stuff
spm_imcalc_ui(grsegs,maskimg,addsegs);

% norm mask
spm_write_sn(maskimg, grmatname,grwrflags);

% smooth mask
spm_smooth(wmaskimg,swmaskimg,par.specsmooth);

% use threshold (truncate)
spm_imcalc_ui(swmaskimg,tswmaskimg,maskthresh);


fprintf('---Specmask COMPLETED for %s---\n',par.substr);



cd(origdir);