function par_makevols(subpar)
% par_makevols(subpar)
% makes efile and runs Gary's makevols.
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% 
% LAST MODIFIED by jbh 7/23/08 to not use system commands (except makevols)
% and to list E files by date

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end

cd(par.subdir);

% make required dirs...
if ~exist(par.funcdir,'dir')
    mkdir(par.funcdir)
else
    movefile(par.funcdir,[par.funcdir '-' date]);
    mkdir(par.funcdir)
end

cd(par.rawdir);
% make efile
d = dir('E*');
efls = vertcat(d.name);
[edts, eord] = sortrows(vertcat(d.datenum)); % always sorted by date!

if exist('efile', 'file')
    movefile('efile', ['efile-' date]);
end
    
fid = fopen('efile','wt');

for W = 1:length(d)
scanname = ['scan' prepend(num2str(W))];    
fprintf(fid,'%s\t%s\n',efls(eord(W),:), scanname);
end

% run makevols
system(['makevols_batch -f ' num2str(par.dropvol) ' efile']);

fclose(fid);

cd(origdir);
