function PM_realign(subpar)
% function par_realign(subpar)
% runs realignment
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% modified from old parscripts by jbh on 7/23/08


origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end

% run realign; generate mean img
fprintf('---Realign for %s---\n',par.substr);

realflag = par.realflag;
reslflag = par.reslflag;
P = par.ascanfiles;
spm_realign(P, realflag);
spm_reslice(P, reslflag);

%save ps
par_print(par);

cd(origdir);
fprintf('---Realign COMPLETED for %s---\n',par.substr);