function par_slicetime(subpar)
% function par_slicetime(subpar)
% run slice timing
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% modified from old parscripts by jbh on 7/23/08

origdir = pwd;
% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end


fprintf('---Slice Timing for %s---\n',par.substr);
cd(par.funcdir);
scanfiles = par.scanfiles; %using a struct was giving me trouble
sliceorder = par.sliceorder;
refslice = par.refslice;
slicetiming =par.slicetiming;
spm_slice_timing(scanfiles, sliceorder, refslice, slicetiming)
cd(origdir);
fprintf('---Slice Timing COMPLETED for %s---\n',par.substr);