function par_segnorm(subpar, snflag)
% par_segnorm(subpar, snflag)
% Segments anatomy and normalizes the gray matter
% 
% subpar refers to either the subject number (in string notation) or 
% the par struct generated by par = par_params(subject)
% 
% snflag is for specifying if you simply want to do one or the other of 
% segmenting/normalizing: specify 's' or 'n'--defaults to both
%
% jbh 7/23/08

origdir = pwd;

% ---load par params if need be---

if isstruct(subpar) % if it is par_params struct
    par = subpar;
else % assume subject string
    par = par_params(subpar);
end

if ~exist('snflag','var'); snflag = 'sn'; end


if ismember('s',snflag)
% ------segment anat----
fprintf('---Segmenting for %s---\n',par.substr);
segfile = par.img2bSeg;
segopts = par.segopts;

% silly options mismatch b/w gui and script!
opts.biasfwhm = par.segbiasfwhm;

res        = spm_preproc(segfile, opts);
[sn,isn]   = spm_prep2sn(res);
[pth,nam]  = spm_fileparts(segfile);
par_savefields(fullfile(pth,[nam '_seg_sn.mat']),sn);
par_savefields(fullfile(pth,[nam '_seg_inv_sn.mat']),isn);
spm_preproc_write(sn, segopts);

fprintf('---Segmenting COMPLETED for %s---\n',par.substr);
end

cd(origdir);

if ismember('n',snflag)
% Estimate and normalize gray matter
fprintf('---Normalizing GrMa for %s---\n',par.substr);

graytemp = par.graytemp;
graysrcimg = par.graysrcimg;
graywrimg = par.graywrimg;
grflags = par.grflags;
grwrflags = par.grwrflags;

[grpth,grnm] = fileparts(graywrimg);
grmatname        = fullfile(grpth,[grnm '_sn.mat']);

spm_normalise(graytemp,graysrcimg,grmatname, '','',grflags);
spm_write_sn(graywrimg, grmatname,grwrflags);

% save ps
par_print(par);

fprintf('---Normalizing GrMa COMPLETED for %s---\n',par.substr);
end

cd(origdir);